[build]
  publish = "."

[[redirects]]
  from = "/petals-and-echoes"
  to = "/games/petals-and-echoes/index.html"
  status = 200

[[redirects]]
  from = "/petals-and-echoes/*"
  to = "/games/petals-and-echoes/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Cache-Control = "public, max-age=3600"
